# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ce616c725f0379cd14634b0d4d1a092214cc164d2f6732b8d9960a85666b36e8bca23a140b5436c29fc56fdc1fcbcc20d91cfe585b3d040c5cd252377b592d4

test:
  secret_key_base: 7a9f66528f29b2d0b85811e2912fd78d764a24e33ad32f8d0faea337180c71045e18a0a0fe352fa5ea229bec06e5904a7426788c3e4a294b73fe8c45d495d637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
